//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_AccessoDB.Account {
    
    
    public partial class OpenAuthProviders {
        
        /// <summary>
        /// Controllo providerDetails.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView providerDetails;
    }
}
